routes/web.php
<?php

Route::get('/', 'HomeController@index')->name('home');

// News Articles
Route::get('/news/', 'NewsController@index')->name('news.index.public');
Route::get('/news/{article}', 'NewsController@show')->name('news.show');

// Courses
Route::get('/courses', 'CoursesController@index')->name('courses.index.public');

//
// Admin Panel
//

Route::group(['namespace' => 'Admin', 'prefix' => 'admin'], function () {
    Route::group(['middleware' => 'guest'], function () {

        // Authentication
        Route::get('/login', 'AuthController@showLogin')->name('login');
        Route::post('/login', 'AuthController@login');

        // User Activation
        Route::get('/users/activate/{token}', 'UsersController@showActivateForm')->name('users.activateForm');
        Route::post('/users/activate', 'UsersController@activateUser')->name('users.activate');
    });

    Route::group(['middleware' => 'auth'], function () {

        // Misc
        Route::get('/logout', 'AuthController@logout')->name('logout');
        Route::get('/', 'HomeController@index')->name('admin.home');
        Route::post('/store', 'HomeController@store');

        // News
        Route::resource('news', 'NewsController', ['except' => 'show', 'parameters' => ['news' => 'article']]);

        // Users
        Route::resource('users', 'UsersController', ['only' => ['index', 'store', 'destroy']]);

        // Courses
        Route::resource('courses', 'CoursesController', ['except' => 'show']);

        // Groups
        Route::resource('groups', 'GroupsController');

        // Students
        Route::resource('students', 'StudentsController');
        Route::get('/students/{student}/email', 'StudentsController@showEmailForm')->name('students.email');
        Route::post('/students/{student}/email', 'StudentsController@emailStudent');
        Route::post('/students/{student}/comments', 'StudentsController@postComment')->name('students.comments');
        Route::post('/students/{student}/leave/{group}', 'StudentsController@leaveGroup')->name('students.leaveGroup');
    });
});

app/Student.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Mail\Mailable;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Storage;

class Student extends Model
{
    protected $guarded = [];

    protected $dates = [
        'created_at',
        'updated_at',
        'birthday',
    ];

    protected static function boot()
    {
        parent::boot();

        static::deleting(function ($student) {
            $student->changePicture();
        });
    }

    public function joinGroup($group)
    {
        return $this->groups()->attach($group);
    }

    public function groups()
    {
        return $this->belongsToMany(Group::class)->withTimestamps();
    }

    public function leaveGroup($group)
    {
        return $this->groups()->detach($group);
    }

    public function syncGroups($groups)
    {
        return $this->groups()->sync($groups);
    }

    public function age()
    {
        return $this->birthday->age;
    }

    public function picture()
    {
        return $this->picture ? Storage::disk('public')->url($this->picture) : config('app.students_default_img');
    }

    public function addComment($request)
    {
        return $this->comments()->create([
            'author_id' => auth()->id(),
            'body'      => $request->body,
        ]);
    }

    public function comments()
    {
        return $this->hasMany(StudentComment::class)->orderBy('created_at', 'DESC');
    }

    public function changePicture($picture = null)
    {
        if ($this->picture) {
            Storage::disk('public')->delete($this->picture);
        }

        $this->picture = $picture;

        return $this;
    }

    public function sendMail(Mailable $mail)
    {
        return Mail::to($this)->send($mail);
    }
}

app/Http/Controllers/Admin/StudentsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Group;
use App\Http\Controllers\Controller;
use App\Http\Requests\StoreStudent;
use App\Http\Requests\StoreStudentComment;
use App\Mail\StudentMail;
use App\Student;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class StudentsController extends Controller
{
    public function index()
    {
        $students = Student::orderBy('name')->get();

        if (request()->expectsJson()) {
            return $students;
        }

        return view('admin.students.index', compact('students'));
    }

    public function destroy(Student $student)
    {
        $student->delete();

        if (request()->expectsJson()) {
            return response()->json([
                'status'  => 'success',
                'message' => __('Student deleted'),
            ]);
        }

        return redirect(route('students.index'))->with('flash', __('Student deleted'));
    }

    public function create()
    {
        return view('admin.students.create', [
            'groups' => Group::all('id', 'name'),
        ]);
    }

    public function edit(Student $student)
    {
        $groups = Group::all('id', 'name');

        return view('admin.students.edit', compact('student', 'groups'));
    }

    public function store(StoreStudent $request)
    {
        $student = new Student();

        if ($request->hasFile('picture')) {
            $student->picture = Storage::disk('public')->put('students', $request->file('picture'));
        }

        $this->fillStudent($student, $request);

        return redirect(route('students.show', $student->id))->with('flash', __('Student saved'));
    }

    public function update(Student $student, StoreStudent $request)
    {
        if ($request->hasFile('picture')) {
            $student->changePicture(Storage::disk('public')->put('students', $request->file('picture')));
        } elseif ($request->no_picture) {
            $student->changePicture();
        }

        $this->fillStudent($student, $request);

        return redirect(route('students.show', $student->id))->with('flash', __('Student updated'));
    }

    public function show($student)
    {
        $student = Student::with(['comments', 'groups'])->findOrFail($student);

        if (request()->expectsJson()) {
            return $student;
        }

        return view('admin.students.show', compact('student'));
    }

    public function showEmailForm(Student $student)
    {
        return view('admin.students.email', compact('student'));
    }

    public function emailStudent(Student $student, Request $request)
    {
        $this->validate($request, [
            'subject' => 'required|max:80',
            'body'    => 'required|min:5',
        ]);

        $student->sendMail(
            new StudentMail($request->subject, $request->body, $student, auth()->user())
        );

        return redirect(route('students.show', $student->id))->with('flash', __('Email send'));
    }

    public function postComment(Student $student, StoreStudentComment $request)
    {
        $student->addComment($request);

        return redirect(route('students.show', $student->id))->with('flash', __('Comment saved'));
    }

    public function leaveGroup(Student $student, Group $group)
    {
        $student->leaveGroup($group);

        if (request()->expectsJson()) {
            return [
                'status'  => 'success',
                'message' => __('Student removed from group'),
            ];
        }
    }

    protected function fillStudent(Student $student, $request)
    {
        $student->fill($request->only('name', 'residence', 'email', 'birthday'))->save();

        $student->syncGroups($request->groups);

        return $student;
    }
}

resources/views/admin/students/create.blade.php
@extends('layout.admin')

@section('meta')
    <title>{{ config('app.name') }} - {{ __('Add Student') }}</title>
@endsection

@section('content')
    <form action="{{ route('students.store') }}" method="POST" enctype="multipart/form-data">
        {{ csrf_field() }}
        @component('layout.partials.panel')
            <div class="row">
                <div class="col-sm-6">
                    <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                        <label for="name">{{ __('Name') }}</label>
                        <input type="text" name="name" class="form-control" id="name" placeholder="{{ __('Name') }}" value="{{ old('name') }}">
                        @if ($errors->has('name'))
                            <span class="help-block">
                                <strong>{{ ucfirst($errors->first('name')) }}</strong>
                            </span>
                        @endif
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group{{ $errors->has('residence') ? ' has-error' : '' }}">
                        <label for="residence">{{ __('Residence') }}</label>
                        <input type="text" name="residence" class="form-control" id="residence" placeholder="{{ __('Residence') }}" value="{{ old('residence') }}">
                        @if ($errors->has('residence'))
                            <span class="help-block">
                                <strong>{{ ucfirst($errors->first('residence')) }}</strong>
                            </span>
                        @endif
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6">
                    <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                        <label for="email">{{ __('E-Mail Address') }}</label>
                        <input type="email" name="email" class="form-control" id="email" placeholder="{{ __('E-Mail Address') }}" value="{{ old('email') }}">
                        @if ($errors->has('email'))
                            <span class="help-block">
                                <strong>{{ ucfirst($errors->first('email')) }}</strong>
                            </span>
                        @endif
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group{{ $errors->has('birthday') ? ' has-error' : '' }}">
                        <label for="birthday">{{ __('Day of birth') }}</label>
                        <input type="date" name="birthday" class="form-control" id="birthday" placeholder="{{ __('Day of birth') }}" value="{{ old('birthday') }}">
                        @if ($errors->has('birthday'))
                            <span class="help-block">
                                <strong>{{ ucfirst($errors->first('birthday')) }}</strong>
                            </span>
                        @endif
                    </div>
                </div>
            </div>
        @endcomponent
        @component('layout.partials.panel')
            <div class="row">
                <div class="col-sm-6">
                    <div class="form-group">
                        <label for="groups">{{ __('Available Groups') }}</label>
                        <select id="groups" class="form-control" size="10" multiple>
                            @foreach($groups as $group)
                                @if(!in_array($group->id, old('groups', [])))
                                    <option value="{{ $group->id }}">{{ $group->name }}</option>
                                @endif
                            @endforeach
                        </select>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group">
                        <label for="groups_to">{{ __('Selected Groups') }}</label>
                        <select name="groups[]" id="groups_to" class="form-control" size="10" multiple>
                            @foreach($groups as $group)
                                @if(in_array($group->id, old('groups', [])))
                                    <option value="{{ $group->id }}">{{ $group->name }}</option>
                                @endif
                            @endforeach
                        </select>
                    </div>
                </div>
            </div>
        @endcomponent
        @component('layout.partials.panel')
            <div class="form-group{{ $errors->has('picture') ? ' has-error' : '' }}">
                <label for="picture">{{ __('Picture') }}</label>
                <input type="file" class="filestyle" name="picture" id="picture">
                @if ($errors->has('picture'))
                    <span class="help-block">
                        <strong>{{ ucfirst($errors->first('picture')) }}</strong>
                    </span>
                @else
                    <span class="help-block">{{ __('Picture must be 1/1 ratio and max 200kb.') }}</span>
                @endif
            </div>
        @endcomponent
        <div class="text-right">
            <button class="btn btn-primary" type="submit">{{ __('Add Student') }}</button>
        </div>
    </form>
@endsection

@include('layout.partials.multiselect', ['multiselect' => '#groups'])
@include('layout.partials.datepicker', ['format' => 'yyyy-mm-dd'])
@include('layout.partials.filestyle')

resources/views/admin/students/edit.blade.php
@extends('layout.admin')

@section('meta')
    <title>{{ config('app.name') }} - {{ __('Edit Student') }} - {{ $student->id }}</title>
@endsection

@section('content')
    <form action="{{ route('students.update', $student->id) }}" method="POST" enctype="multipart/form-data">
        {{ csrf_field() }}
        {{ method_field('PATCH') }}
        @component('layout.partials.panel')
            <div class="row">
                <div class="col-sm-6">
                    <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                        <label for="name">{{ __('Name') }}</label>
                        <input type="text" name="name" class="form-control" id="name" placeholder="{{ __('Name') }}" value="{{ old('name', $student->name) }}">
                        @if ($errors->has('name'))
                            <span class="help-block">
                                <strong>{{ ucfirst($errors->first('name')) }}</strong>
                            </span>
                        @endif
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group{{ $errors->has('residence') ? ' has-error' : '' }}">
                        <label for="residence">{{ __('Residence') }}</label>
                        <input type="text" name="residence" class="form-control" id="residence" placeholder="{{ __('Residence') }}" value="{{ old('residence', $student->residence) }}">
                        @if ($errors->has('residence'))
                            <span class="help-block">
                                <strong>{{ ucfirst($errors->first('residence')) }}</strong>
                            </span>
                        @endif
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6">
                    <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                        <label for="email">{{ __('E-Mail Address') }}</label>
                        <input type="email" name="email" class="form-control" id="email" placeholder="{{ __('E-Mail Address') }}" value="{{ old('email', $student->email) }}">
                        @if ($errors->has('email'))
                            <span class="help-block">
                                <strong>{{ ucfirst($errors->first('email')) }}</strong>
                            </span>
                        @endif
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group{{ $errors->has('birthday') ? ' has-error' : '' }}">
                        <label for="birthday">{{ __('Day of birth') }}</label>
                        <input type="date" name="birthday" class="form-control" id="birthday" placeholder="{{ __('Day of birth') }}" value="{{ old('birthday', $student->birthday->toDateString()) }}">
                        @if ($errors->has('birthday'))
                            <span class="help-block">
                                <strong>{{ ucfirst($errors->first('birthday')) }}</strong>
                            </span>
                        @endif
                    </div>
                </div>
            </div>
        @endcomponent
        @component('layout.partials.panel')
            <div class="row">
                <div class="col-sm-6">
                    <div class="form-group">
                        <label for="groups">{{ __('Available Groups') }}</label>
                        <select id="groups" class="form-control" size="10" multiple>
                            @foreach($groups as $group)
                                @if(!in_array($group->id, old('groups', $student->groups->pluck('id')->toArray())))
                                    <option value="{{ $group->id }}">{{ $group->name }}</option>
                                @endif
                            @endforeach
                        </select>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group">
                        <label for="groups_to">{{ __('Selected Groups') }}</label>
                        <select name="groups[]" id="groups_to" class="form-control" size="10" multiple>
                            @foreach($groups as $group)
                                @if(in_array($group->id, old('groups', $student->groups->pluck('id')->toArray())))
                                    <option value="{{ $group->id }}">{{ $group->name }}</option>
                                @endif
                            @endforeach
                        </select>
                    </div>
                </div>
            </div>
        @endcomponent
        @component('layout.partials.panel')
            <div class="form-group{{ $errors->has('picture') ? ' has-error' : '' }}">
                <label for="picture">{{ __('Picture') }}</label>
                <input type="file" class="filestyle" name="picture" id="picture">
                @if ($errors->has('picture'))
                    <span class="help-block">
                        <strong>{{ ucfirst($errors->first('picture')) }}</strong>
                    </span>
                @else
                    <span class="help-block">{{ __('Picture must be 1/1 ratio and max 200kb.') }}</span>
                @endif
            </div>
            <div class="form-group">
                <label class="checkbox-inline"><input type="checkbox" name="no_picture" value="1"{{ old('no_picture') ? ' checked' : '' }}>{{ __('Delete profile picture') }}</label>
            </div>
        @endcomponent
        <div class="text-right">
            <button id="delete-button" class="btn btn-danger">{{ __('Delete') }}</button>
            <button class="btn btn-primary" type="submit">{{ __('Edit Student') }}</button>
        </div>
    </form>
    <form id="delete-form" action="{{ route('students.destroy', $student->id) }}" method="post">
        {{ csrf_field() }}
        {{ method_field('DELETE') }}
    </form>
@endsection

@include('layout.partials.multiselect', ['multiselect' => '#groups'])
@include('layout.partials.datepicker', ['format' => 'yyyy-mm-dd'])
@include('layout.partials.filestyle')

@push('js')
    <script>
        $('#delete-button').click(function(e) {
            e.preventDefault();

            if(confirm('{{ __('Delete Student') }}?')) {
                $('#delete-form').submit();
            }
        })
    </script>
@endpush

resources/views/admin/students/email.blade.php
@extends('layout.admin')

@section('meta')
    <title>{{ config('app.name') }} - {{ __('Send Mail') }} - {{ $student->name }}</title>
@endsection

@section('content')
    <form action="{{ route('students.email', $student->id) }}" method="POST">
        {{ csrf_field() }}
        @component('layout.partials.panel')
            @slot('heading')
                <span class="is-bold">{{ __('Send email to') }} {{ $student->name }}</span>
            @endslot
            <div class="form-group{{ $errors->has('subject') ? ' has-error' : '' }}">
                <label for="subject">{{ __('Subject') }}</label>
                <input type="text" name='subject' class="form-control" id="subject" placeholder="{{ __('Subject') }}" value="{{ old('subject') }}">
                @if($errors->has('subject'))
                    <span class="help-block">
                        <strong>{{ ucfirst($errors->first('subject')) }}</strong>
                    </span>
                @endif
            </div>
            <div class="form-group{{ $errors->has('body') ? ' has-error' : '' }}">
                <label for="body">{{ __('Content') }}</label>
                <textarea class="form-control not-resizable" name="body" id="body" rows="15" placeholder="{{ __('Content') }}">{{ old('body') }}</textarea>
                @if($errors->has('body'))
                    <span class="help-block">
                        <strong>{{ ucfirst($errors->first('body')) }}</strong>
                    </span>
                @endif
            </div>
        @endcomponent
        <div class="text-right">
            <button type="submit" class="btn btn-primary">{{ __('Send Email') }}</button>
        </div>
    </form>
@endsection

resources/views/admin/students/index.blade.php
@extends('layout.admin')

@section('meta')
    <title>{{ config('app.name') }} - {{ __('Students') }}</title>
@endsection

@section('content')
    <div class="mb10 text-right">
        <a href="{{ route('students.create') }}">
            <button class="btn btn-primary">{{ __('Add Student') }}</button>
        </a>
    </div>

    @component('layout.partials.panel')
        <table id="students" class="table table-striped table-hover table-responsive">
            <thead>
                <th>{{ __('Name') }}</th>
                <th>{{ __('E-Mail Address') }}</th>
                <th>{{ __('Age') }}</th>
                <th>{{ __('Residence') }}</th>
                <th>{{ __('Created at') }}</th>
                <th>{{ __('Updated at') }}</th>
                <th></th>
            </thead>
            <tbody>
                @foreach($students as $student)
                    <tr>
                        <td><a href="{{ route('students.show', $student->id) }}">{{ $student->name }}</a></td>
                        <td><a href="{{ route('students.email', $student->id) }}">{{ $student->email }}</a></td>
                        <td><span title="{{ $student->birthday->toFormattedDateString() }}">{{ $student->age() }}</span></td>
                        <td>{{ $student->residence }}</td>
                        <td>{{ $student->created_at }}</td>
                        <td>{{ $student->updated_at }}</td>
                        <td class="text-center">
                            <a href="{{ route('students.edit', $student->id) }}" title="{{ __('Edit') }}"><span class="glyphicon glyphicon-edit" aria-hidden="true"></span></a>
                            <a class="delete" href="#" data-id="{{ $student->id }}" title="{{ __('Delete') }}"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></a>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @endcomponent
@endsection

@include('layout.partials.datatables', ['table' => '#students', 'features' => true])

@push('js')
<script>
    $('.delete').click(function (e) {
        e.preventDefault();

        if (confirm('{{ __('Delete Student') }}?')) {
            $.ajax({
                url: '/admin/students/' + $(this).data('id'),
                method: 'POST',
                data: {
                    '_token': '{{ csrf_token() }}',
                    '_method': 'DELETE'
                }
            }).done(function (data) {
                $(this).closest('tr').remove();
                alertify.notify(data.message, data.status);
            }.bind(this))
        }
    });
</script>
@endpush

resources/views/admin/students/show.blade.php
@extends('layout.admin')

@section('meta')
    <title>{{ config('app.name') }} - {{ $student->name }}</title>
@endsection

@section('content')
    <div class="row">
        <div class="col-sm-4 col-md-3">
            @component('layout.partials.panel')
                @slot('heading')
                    <span class="is-bold">{{ $student->name }}</span>
                @endslot
                <div class="mb10">
                    <img src="{{ $student->picture() }}" alt="{{ $student->name }}" class="img-thumbnail" width="100%" height="100%">
                </div>
                <div class="list-group mb10">
                    <div class="list-group-item">
                        <h5 class="list-group-item-heading is-bold">{{ __('Day of birth') }}</h5>
                        <p class="list-group-item-text">{{ $student->birthday->toDateString() }} ({{ $student->age() }})</p>
                    </div>
                    <div class="list-group-item">
                        <h5 class="list-group-item-heading is-bold">{{ __('Residence') }}</h5>
                        <p class="list-group-item-text">{{ $student->residence }}</p>
                    </div>
                    <div class="list-group-item">
                        <h5 class="list-group-item-heading is-bold">{{ __('E-Mail Address') }}</h5>
                        <p class="list-group-item-text"><a href="{{ route('students.email', $student->id) }}">{{ $student->email }}</a></p>
                    </div>
                    <div class="list-group-item">
                        <h5 class="list-group-item-heading is-bold">{{ __('Created at') }}</h5>
                        <p class="list-group-item-text">{{ $student->created_at->toDayDateTimeString() }}</p>
                    </div>
                    <div class="list-group-item">
                        <h5 class="list-group-item-heading is-bold">{{ __('Updated at') }}</h5>
                        <p class="list-group-item-text">{{ $student->updated_at->toDayDateTimeString() }}</p>
                    </div>
                    <div class="list-group-item">
                        <h5 class="list-group-item-heading is-bold">{{ __('Groups') }}</h5>
                        @forelse($student->groups as $group)
                            <li><a href="{{ route('groups.show', $group->id) }}">{{ $group->name }}</a></li>
                        @empty
                            <li>{{ __('No groups') }}</li>
                        @endforelse
                    </div>
                </div>
                <div>
                    <div class="mb10">
                        <a class="btn btn-primary btn-block" href="{{ route('students.edit', $student->id) }}">{{ __('Edit Student') }}</a>
                    </div>
                    <form action="{{ route('students.destroy', $student->id) }}" method="POST">
                        {{ csrf_field() }}
                        {{ method_field('DELETE') }}
                        <button id="delete" type="submit" class="btn btn-danger btn-block">{{ __('Delete Student') }}</button>
                    </form>
                </div>
            @endcomponent
        </div>
        <div class="col-sm-8 col-md-9">
            @component('layout.partials.panel')
                @slot('heading')
                    <span class="is-bold">{{ __('Comment') }}</span>
                @endslot
                <form action="{{ route('students.comments', $student->id) }}" method="post">
                    {{ csrf_field() }}
                    <div class="form-group{{ $errors->has('body') ? ' has-error' : '' }}">
                        <textarea class="form-control not-resizable" name="body" id="body" rows="5" placeholder="{{ __('Comment') }}">{{ old('body') }}</textarea>
                        @if ($errors->has('body'))
                            <span class="help-block">
                                <strong>{{ ucfirst($errors->first('body')) }}</strong>
                            </span>
                        @endif
                    </div>
                    <div class="text-right">
                        <button class="btn btn-primary">{{ __('Post Comment') }}</button>
                    </div>
                </form>
            @endcomponent
            @foreach($student->comments as $comment)
                @component('layout.partials.panel', ['id' => "comment-{$comment->id}"])
                    @slot('heading')
                        <span class="is-bold">{{ $comment->author->name }}</span> {{ __('wrote') }} {{ $comment->created_at->diffForHumans() }}.
                    @endslot
                    {{ $comment->body }}
                @endcomponent
            @endforeach
        </div>
    </div>
@endsection

@push('js')
    <script>
        $('#delete').click(function(e) {
            e.preventDefault();

            if (confirm('{{ __('Delete Student') }}?')) {
                $(this).closest('form').submit();
            }
        })
    </script>
@endpush