routes/web.php
<?php

Route::get('/', 'HomeController@index')->name('home');

// News Articles
Route::get('/news/', 'NewsController@index')->name('news.index.public');
Route::get('/news/{article}', 'NewsController@show')->name('news.show');

// Courses
Route::get('/courses', 'CoursesController@index')->name('courses.index.public');

//
// Admin Panel
//

Route::group(['namespace' => 'Admin', 'prefix' => 'admin'], function () {
    Route::group(['middleware' => 'guest'], function () {

        // Authentication
        Route::get('/login', 'AuthController@showLogin')->name('login');
        Route::post('/login', 'AuthController@login');

        // User Activation
        Route::get('/users/activate/{token}', 'UsersController@showActivateForm')->name('users.activateForm');
        Route::post('/users/activate', 'UsersController@activateUser')->name('users.activate');
    });

    Route::group(['middleware' => 'auth'], function () {

        // Misc
        Route::get('/logout', 'AuthController@logout')->name('logout');
        Route::get('/', 'HomeController@index')->name('admin.home');
        Route::post('/store', 'HomeController@store');

        // News
        Route::resource('news', 'NewsController', ['except' => 'show', 'parameters' => ['news' => 'article']]);

        // Users
        Route::resource('users', 'UsersController', ['only' => ['index', 'store', 'destroy']]);

        // Courses
        Route::resource('courses', 'CoursesController', ['except' => 'show']);

        // Groups
        Route::resource('groups', 'GroupsController');

        // Students
        Route::resource('students', 'StudentsController');
        Route::get('/students/{student}/email', 'StudentsController@showEmailForm')->name('students.email');
        Route::post('/students/{student}/email', 'StudentsController@emailStudent');
        Route::post('/students/{student}/comments', 'StudentsController@postComment')->name('students.comments');
        Route::post('/students/{student}/leave/{group}', 'StudentsController@leaveGroup')->name('students.leaveGroup');
    });
});

app/Group.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Group extends Model
{
    protected $guarded = [];

    protected $dates = [
        'created_at',
        'updated_at',
        'starts_at',
        'ends_at',
    ];

    public function course()
    {
        return $this->belongsTo(Course::class);
    }

    public function students()
    {
        return $this->belongsToMany(Student::class)->withTimestamps()->orderBy('name');
    }

    public function addStudent(Student $student)
    {
        return $this->students()->attach($student);
    }

    public function removeStudent(Student $student)
    {
        return $this->students()->detach($student);
    }

    public function syncStudents($students)
    {
        return $this->students()->sync($students);
    }
}

app/Http/Controllers/Admin/GroupsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Course;
use App\Group;
use App\Http\Controllers\Controller;
use App\Http\Requests\StoreGroup;
use App\Student;
use Illuminate\Http\Request;

class GroupsController extends Controller
{
    public function index(Request $request)
    {
        $groups = Group::with('course')->withCount('students');

        if ($request->has('course')) {
            $groups->where('course_id', $request->get('course'));
        }

        $groups = $groups->get();

        if ($request->ajax() || $request->wantsJson()) {
            return $groups;
        }

        return view('admin.groups.index', compact('groups'));
    }

    public function show($group)
    {
        $group = Group::with(['students', 'course'])->findOrFail($group);

        return view('admin.groups.show', compact('group'));
    }

    public function create()
    {
        return view('admin.groups.create', [
            'courses'  => Course::all(['id', 'name'])->sortBy('name.'.config('app.locale')),
            'students' => Student::orderBy('name')->get(['id', 'name']),
        ]);
    }

    public function store(StoreGroup $request)
    {
        $group = Group::create($request->except('students'));

        $group->syncStudents($request->students);

        return redirect(route('groups.show', $group->id))->with('flash', __('Group saved'));
    }

    public function update(Group $group, StoreGroup $request)
    {
        $group->update($request->except('students'));

        $group->syncStudents($request->students);

        return redirect(route('groups.show', $group->id))->with('flash', __('Group updated'));
    }

    public function destroy(Group $group, Request $request)
    {
        $group->delete();

        if ($request->ajax() || $request->wantsJson()) {
            return response()->json([
                'status'  => 'success',
                'message' => __('Group deleted'),
            ]);
        }

        return redirect(route('groups.index'))->with('flash', __('Group deleted'));
    }

    public function edit($group)
    {
        $group = Group::with('students')->findOrFail($group);

        return view('admin.groups.edit', [
            'group'    => $group,
            'courses'  => Course::all(['id', 'name'])->sortBy('name.'.config('app.locale')),
            'students' => Student::orderBy('name')->get(['id', 'name']),
        ]);
    }
}

resources/views/admin/groups/create.blade.php
@extends('layout.admin')

@section('meta')
    <title>{{ config('app.name') }} - {{ __('Add Group') }}</title>
@endsection

@section('content')
    <form action="{{ route('groups.store') }}" method="POST">
        {{ csrf_field() }}
        @component('layout.partials.panel')
            <div class="row">
                <div class="col-sm-6">
                    <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                        <label for="name">{{ __('Name') }}</label>
                        <input type="text" name="name" class="form-control" id="name" placeholder="{{ __('Name') }}" value="{{ old('name') }}">
                        @if ($errors->has('name'))
                            <span class="help-block">
                                <strong>{{ ucfirst($errors->first('name')) }}</strong>
                            </span>
                        @endif
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group{{ $errors->has('course_id') ? ' has-error' : '' }}">
                        <label for="course_id">{{ __('Course') }}</label>
                        <select name="course_id" id="course_id" class="form-control">
                            <option disabled{{ old('course_id') ? '' : ' selected' }}>{{ __('Select a course') }}</option>
                            @foreach($courses as $course)
                                <option value="{{ $course->id }}" {{ old('course_id') == $course->id ? 'selected' : '' }}>{{ $course->asLocale('name') }}</option>
                            @endforeach
                        </select>
                        @if ($errors->has('course_id'))
                            <span class="help-block">
                                <strong>{{ ucfirst($errors->first('course_id')) }}</strong>
                            </span>
                        @endif
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6">
                    <div class="form-group{{ $errors->has('starts_at') ? ' has-error' : '' }}">
                        <label for="starts_at">{{ __('Starts on') }}</label>
                        <input type="date" name="starts_at" class="form-control" id="starts_at" placeholder="{{ __('Starts on') }}" value="{{ old('starts_at') }}">
                        @if ($errors->has('starts_at'))
                            <span class="help-block">
                                <strong>{{ ucfirst($errors->first('starts_at')) }}</strong>
                            </span>
                        @endif
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group{{ $errors->has('ends_at') ? ' has-error' : '' }}">
                        <label for="ends_at">{{ __('Ends on') }}</label>
                        <input type="date" name="ends_at" class="form-control" id="ends_at" placeholder="{{ __('Ends on') }}" value="{{ old('ends_at') }}">
                        @if ($errors->has('ends_at'))
                            <span class="help-block">
                                <strong>{{ ucfirst($errors->first('ends_at')) }}</strong>
                            </span>
                        @endif
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    <div class="form-group">
                        <label for="comment">{{ __('Comment') }}</label>
                        <textarea name="comment" id="comment" rows="5" class="form-control not-resizable" placeholder="{{ __('Comment') }}">{{ old('comment') }}</textarea>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    <div class="form-group{{ $errors->has('status') ? ' has-error' : '' }}">
                        <label for="status">{{ __('Group Status') }}</label>
                        <select name="status" id="status" class="form-control">
                            <option disabled{{ old('status') ? '' : ' selected' }}>{{ __('Select a status') }}</option>
                            @foreach(config('app.group_status') as $status)
                                <option value="{{ $status }}" {{ old('status') == $status ? 'selected' : '' }}>{{ __(ucfirst($status)) }}</option>
                            @endforeach
                        </select>
                        @if ($errors->has('status'))
                            <span class="help-block">
                                <strong>{{ ucfirst($errors->first('status')) }}</strong>
                            </span>
                        @endif
                    </div>
                </div>
            </div>
        @endcomponent
        @component('layout.partials.panel')
            <div class="row">
                <div class="col-sm-6">
                    <div class="form-group">
                        <label for="students">{{ __('Available Students') }}</label>
                        <select id="students" class="form-control" size="10" multiple>
                            @foreach($students as $student)
                                @if(!in_array($student->id, old('students', [])))
                                    <option value="{{ $student->id }}">{{ $student->name }}</option>
                                @endif
                            @endforeach
                        </select>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group">
                        <label for="students_to">{{ __('Selected Students') }}</label>
                        <select name="students[]" id="students_to" class="form-control" size="10" multiple>
                            @foreach($students as $student)
                                @if(in_array($student->id, old('students', [])))
                                    <option value="{{ $student->id }}">{{ $student->name }}</option>
                                @endif
                            @endforeach
                        </select>
                    </div>
                </div>
            </div>
        @endcomponent
        <div class="text-right">
            <button class="btn btn-primary" type="submit">{{ __('Add Group') }}</button>
        </div>
    </form>
@endsection

@include('layout.partials.multiselect', ['multiselect' => '#students'])
@include('layout.partials.datepicker', ['format' => 'yyyy-mm-dd'])

resources/views/admin/groups/edit.blade.php
@extends('layout.admin')

@section('meta')
    <title>{{ config('app.name') }} - {{ __('Edit Group') }} - {{ $group->name }}</title>
@endsection

@section('content')
    <form action="{{ route('groups.update', $group->id) }}" method="post">
        {{ csrf_field() }}
        {{ method_field('PATCH') }}
        @component('layout.partials.panel')
            <div class="row">
                <div class="col-sm-6">
                    <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                        <label for="name">{{ __('Name') }}</label>
                        <input type="text" name="name" class="form-control" id="name" placeholder="{{ __('Name') }}" value="{{ old('name', $group->name) }}">
                        @if ($errors->has('name'))
                            <span class="help-block">
                                <strong>{{ ucfirst($errors->first('name')) }}</strong>
                            </span>
                        @endif
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group{{ $errors->has('course_id') ? ' has-error' : '' }}">
                        <label for="course_id">{{ __('Course') }}</label>
                        <select name="course_id" id="course_id" class="form-control">
                            <option disabled{{ old('course_id', $group->course_id) ? '' : ' selected' }}>{{ __('Select a course') }}</option>
                            @foreach($courses as $course)
                                <option value="{{ $course->id }}" {{ old('course_id', $group->course_id) == $course->id ? 'selected' : '' }}>{{ $course->asLocale('name') }}</option>
                            @endforeach
                        </select>
                        @if ($errors->has('course_id'))
                            <span class="help-block">
                                <strong>{{ ucfirst($errors->first('course_id')) }}</strong>
                            </span>
                        @endif
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6">
                    <div class="form-group{{ $errors->has('starts_at') ? ' has-error' : '' }}">
                        <label for="starts_at">{{ __('Starts on') }}</label>
                        <input type="date" name="starts_at" class="form-control" id="starts_at" placeholder="{{ __('Starts on') }}" value="{{ old('starts_at', $group->starts_at->toDateString()) }}">
                        @if ($errors->has('starts_at'))
                            <span class="help-block">
                                <strong>{{ ucfirst($errors->first('starts_at')) }}</strong>
                            </span>
                        @endif
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group{{ $errors->has('ends_at') ? ' has-error' : '' }}">
                        <label for="ends_at">{{ __('Ends on') }}</label>
                        <input type="date" name="ends_at" class="form-control" id="ends_at" placeholder="{{ __('Ends on') }}" value="{{ old('ends_at', $group->ends_at->toDateString()) }}">
                        @if ($errors->has('ends_at'))
                            <span class="help-block">
                                <strong>{{ ucfirst($errors->first('ends_at')) }}</strong>
                            </span>
                        @endif
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    <div class="form-group">
                        <label for="comment">{{ __('Comment') }}</label>
                        <textarea name="comment" id="comment" rows="5" class="form-control not-resizable" placeholder="{{ __('Comment') }}">{{ old('comment', $group->comment) }}</textarea>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    <div class="form-group{{ $errors->has('status') ? ' has-error' : '' }}">
                        <label for="status">{{ __('Group Status') }}</label>
                        <select name="status" id="status" class="form-control">
                            <option disabled{{ old('status', $group->status) ? '' : ' selected' }}>{{ __('Select a status') }}</option>
                            @foreach(config('app.group_status') as $status)
                                <option value="{{ $status }}" {{ old('status', $group->status) == $status ? 'selected' : '' }}>{{ __(ucfirst($status)) }}</option>
                            @endforeach
                        </select>
                        @if ($errors->has('status'))
                            <span class="help-block">
                                <strong>{{ ucfirst($errors->first('status')) }}</strong>
                            </span>
                        @endif
                    </div>
                </div>
            </div>
        @endcomponent
        @component('layout.partials.panel')
            <div class="row">
                <div class="col-sm-6">
                    <div class="form-group">
                        <label for="students">{{ __('Available Students') }}</label>
                        <select id="students" class="form-control" size="10" multiple>
                            @foreach($students as $student)
                                @if(!in_array($student->id, old('students', $group->students->pluck('id')->toArray())))
                                    <option value="{{ $student->id }}">{{ $student->name }}</option>
                                @endif
                            @endforeach
                        </select>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group">
                        <label for="students_to">{{ __('Selected Students') }}</label>
                        <select name="students[]" id="students_to" class="form-control" size="10" multiple>
                            @foreach($students as $student)
                                @if(in_array($student->id, old('students', $group->students->pluck('id')->toArray())))
                                    <option value="{{ $student->id }}">{{ $student->name }}</option>
                                @endif
                            @endforeach
                        </select>
                    </div>
                </div>
            </div>
        @endcomponent
        <div class="text-right">
            <button id="delete-button" class="btn btn-danger">{{ __('Delete') }}</button>
            <button class="btn btn-primary" type="submit">{{ __('Edit Group') }}</button>
        </div>
    </form>
    <form id="delete-form" action="{{ route('groups.destroy', $group->id) }}" method="POST">
        {{ csrf_field() }}
        {{ method_field('DELETE') }}
    </form>
@endsection

@push('js')
    <script>
        $('#delete-button').click(function(e) {
            e.preventDefault();

            if(confirm('{{ __('Delete Group') }}?')) {
                $('#delete-form').submit();
            }
        });
    </script>
@endpush

@include('layout.partials.multiselect', ['multiselect' => '#students'])
@include('layout.partials.datepicker', ['format' => 'yyyy-mm-dd'])

resources/views/admin/groups/index.blade.php
@extends('layout.admin')

@section('meta')
    <title>{{ config('app.name') }} - {{ __('Groups') }}</title>
@endsection

@section('content')
    <div class="mb10 text-right">
        <a href="{{ route('groups.create') }}">
            <button class="btn btn-primary">{{ __('Add Group') }}</button>
        </a>
    </div>

    @component('layout.partials.panel')
        <table id="groups" class="table table-striped table-hover table-responsive">
            <thead>
                <th>{{ __('Name') }}</th>
                <th>{{ __('Course') }}</th>
                <th>{{ __('Students') }}</th>
                <th>{{ __('Status') }}</th>
                <th>{{ __('Created at') }}</th>
                <th>{{ __('Updated at') }}</th>
                <th></th>
            </thead>
            <tbody>
                @foreach($groups as $group)
                    <tr>
                        <td><a href="{{ route('groups.show', $group->id) }}">{{ $group->name }}</a></td>
                        <td><a href="{{ route('courses.edit', $group->course_id) }}">{{ $group->course->asLocale('name') }}</a></td>
                        <td>{{ $group->students_count }}</td>
                        <td>{{ __(ucfirst($group->status)) }}</td>
                        <td>{{ $group->created_at }}</td>
                        <td>{{ $group->updated_at }}</td>
                        <td class="text-center">
                            <a href="{{ route('groups.edit', $group->id) }}" title="{{ __('Edit') }}"><span class="glyphicon glyphicon-edit" aria-hidden="true"></span></a>
                            <a class="delete" href="#delete" data-id="{{ $group->id }}" title="{{ __('Delete') }}"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></a>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @endcomponent
@endsection

@include('layout.partials.datatables', ['table' => '#groups', 'features' => true])

@push('js')
<script>
    $('.delete').click(function (e) {
        e.preventDefault();

        if (confirm('{{ __('Delete Group') }}?')) {
            $.ajax({
                url: '/admin/groups/' + $(this).data('id'),
                method: 'POST',
                data: {
                    '_token': '{{ csrf_token() }}',
                    '_method': 'DELETE'
                }
            }).done(function (data) {
                $(this).closest('tr').remove();
                alertify.notify(data.message, data.status);
            }.bind(this))
        }
    });
</script>
@endpush

resources/views/admin/groups/show.blade.php
@extends('layout.admin')

@section('meta')
    <title>{{ config('app.name') }} - {{ $group->name }}</title>
@endsection

@section('content')
    <div class="row">
        <div class="col-sm-3">
            @component('layout.partials.panel')
                @slot('heading')
                    <span class="is-bold">{{ $group->name }}</span>
                @endslot
                <div class="list-group mb10">
                    <div class="list-group-item">
                        <h5 class="list-group-item-heading is-bold">{{ __('Course') }}</h5>
                        <p class="list-group-item-text">
                            <a href="{{ route('courses.edit', $group->course->id) }}">{{ $group->course->asLocale('name') }}</a>
                        </p>
                    </div>
                    <div class="list-group-item">
                        <h5 class="list-group-item-heading is-bold">{{ __('Starts on') }}</h5>
                        <p class="list-group-item-text">
                            {{ $group->starts_at->toFormattedDateString() }}
                        </p>
                    </div>
                    <div class="list-group-item">
                        <h5 class="list-group-item-heading is-bold">{{ __('Ends on') }}</h5>
                        <p class="list-group-item-text">
                            {{ $group->ends_at->toFormattedDateString() }}
                        </p>
                    </div>
                    <div class="list-group-item">
                        <h5 class="list-group-item-heading is-bold">{{ __('Duration') }}</h5>
                        <p class="list-group-item-text">
                            {{ $group->ends_at->diffForHumans($group->starts_at, true) }}
                        </p>
                    </div>
                    <div class="list-group-item">
                        <h5 class="list-group-item-heading is-bold">{{ __('Group Status') }}</h5>
                        <p class="list-group-item-text">
                            {{ ucfirst($group->status) }}
                        </p>
                    </div>
                    <div class="list-group-item">
                        <h5 class="list-group-item-heading is-bold">{{ __('Number of students') }}</h5>
                        <p class="list-group-item-text">
                            {{ $group->students->count() }}
                        </p>
                    </div>
                </div>
                <div>
                    <div class="mb10">
                        <a class="btn btn-primary btn-block" href="{{ route('groups.edit', $group->id) }}">{{ __('Edit Group') }}</a>
                    </div>
                    <form action="{{ route('groups.destroy', $group->id) }}" method="POST">
                        {{ csrf_field() }}
                        {{ method_field('DELETE') }}
                        <button type="submit" class="btn btn-danger btn-block">{{ __('Delete Group') }}</button>
                    </form>
                </div>
            @endcomponent
        </div>
        <div class="col-sm-9">
            @if($group->comment)
                @component('layout.partials.panel')
                    @slot('heading')
                        <span class="is-bold">{{ __('Comment') }}</span>
                    @endslot
                    {{ $group->comment }}
                @endcomponent
            @endif
            @component('layout.partials.panel')
                @slot('heading')
                    <span class="is-bold">{{ __('Students') }}</span>
                @endslot
                <table id="students" class="table table-striped table-hover">
                    <thead>
                        <th>{{ __('Name') }}</th>
                        <th>{{ __('E-Mail Address') }}</th>
                        <th>{{ __('Added on') }}</th>
                        <th></th>
                    </thead>
                    <tbody>
                        @foreach($group->students as $student)
                            <tr>
                                <td><a href="{{ route('students.show', $student->id) }}">{{ $student->name }}</a></td>
                                <td><a href="{{ route('students.email', $student->id) }}">{{ $student->email }}</a></td>
                                <td>{{ $student->pivot->created_at }}</td>
                                <td class="text-center">
                                    <a class="detach" data-id="{{ $student->id }}" href="#detach" title="{{ __('Remove from group') }}"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></a>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            @endcomponent
        </div>
    </div>
@endsection

@include('layout.partials.datatables', ['table' => '#students', 'features' => false])

@push('js')
    <script>
        $('.detach').click(function (e) {
            e.preventDefault();

            if (confirm('{{ __('Remove student from group') }}?')) {
                $.ajax({
                    url: '/admin/students/' + $(this).data('id') + '/leave/{{ $group->id }}',
                    method: 'POST',
                    data: {
                        '_token': '{{ csrf_token() }}'
                    }
                }).done(function (data) {
                    $(this).closest('tr').remove();
                    alertify.notify(data.message, data.status)
                }.bind(this))
            }
        });
    </script>
@endpush