routes/web.php
<?php

Route::get('/', 'HomeController@index')->name('home');

// News Articles
Route::get('/news/', 'NewsController@index')->name('news.index.public');
Route::get('/news/{article}', 'NewsController@show')->name('news.show');

// Courses
Route::get('/courses', 'CoursesController@index')->name('courses.index.public');

//
// Admin Panel
//

Route::group(['namespace' => 'Admin', 'prefix' => 'admin'], function () {
    Route::group(['middleware' => 'guest'], function () {

        // Authentication
        Route::get('/login', 'AuthController@showLogin')->name('login');
        Route::post('/login', 'AuthController@login');

        // User Activation
        Route::get('/users/activate/{token}', 'UsersController@showActivateForm')->name('users.activateForm');
        Route::post('/users/activate', 'UsersController@activateUser')->name('users.activate');
    });

    Route::group(['middleware' => 'auth'], function () {

        // Misc
        Route::get('/logout', 'AuthController@logout')->name('logout');
        Route::get('/', 'HomeController@index')->name('admin.home');
        Route::post('/store', 'HomeController@store');

        // News
        Route::resource('news', 'NewsController', ['except' => 'show', 'parameters' => ['news' => 'article']]);

        // Users
        Route::resource('users', 'UsersController', ['only' => ['index', 'store', 'destroy']]);

        // Courses
        Route::resource('courses', 'CoursesController', ['except' => 'show']);

        // Groups
        Route::resource('groups', 'GroupsController');

        // Students
        Route::resource('students', 'StudentsController');
        Route::get('/students/{student}/email', 'StudentsController@showEmailForm')->name('students.email');
        Route::post('/students/{student}/email', 'StudentsController@emailStudent');
        Route::post('/students/{student}/comments', 'StudentsController@postComment')->name('students.comments');
        Route::post('/students/{student}/leave/{group}', 'StudentsController@leaveGroup')->name('students.leaveGroup');
    });
});

app/Http/Controllers/Admin/CoursesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Course;
use App\Http\Controllers\Controller;
use App\Http\Requests\StoreCourse;
use Illuminate\Http\Request;

class CoursesController extends Controller
{
    public function store(StoreCourse $request)
    {
        Course::create(
            $request->only('name', 'price', 'description', 'visible', 'lessons')
        );

        return redirect(route('courses.index'))->with('flash', __('Course saved'));
    }

    public function create()
    {
        return view('admin.courses.create', [
            'locales'  => config('app.locales'),
            'fallback' => config('app.fallback_locale'),
        ]);
    }

    public function index(Request $request)
    {
        $courses = Course::withCount('groups')->orderBy('name')->get();

        if ($request->ajax() || $request->wantsJson()) {
            return $courses;
        }

        return view('admin.courses.index', compact('courses'));
    }

    public function edit(Course $course)
    {
        return view('admin.courses.edit', [
            'course'   => $course,
            'locales'  => config('app.locales'),
            'fallback' => config('app.fallback_locale'),
        ]);
    }

    public function update(Course $course, StoreCourse $request)
    {
        $course->update($request->toArray());

        return redirect(route('courses.index'))->with('flash', __('Course updated'));
    }

    public function destroy(Course $course, Request $request)
    {
        $course->delete();

        if ($request->ajax() || $request->wantsJson()) {
            return response()->json([
                'status'  => 'success',
                'message' => __('Course deleted'),
            ]);
        }

        return redirect(route('courses.index'))->with('flash', __('Course deleted'));
    }
}

app/Http/Controllers/CoursesController.php
<?php

namespace App\Http\Controllers;

use App\Course;

class CoursesController extends Controller
{
    public function index()
    {
        $courses = Course::visible()->orderBy('name')->get();

        return view('courses.index', compact('courses'));
    }
}

resources/views/admin/courses/create.blade.php
@extends('layout.admin')

@section('meta')
    <title>{{ config('app.name') }} - {{ __('Add Course') }}</title>
@endsection

@section('content')
    <form action="{{ route('courses.store') }}" method="post">
        {{ csrf_field() }}
        <ul class="nav nav-tabs" role="tablist">

            @foreach($locales as $locale)
                <li role="presentation" {!! $locale == $fallback ? 'class="active"' : '' !!}>
                    <a role="tab" aria-controls="{{ $locale }}" data-toggle="tab" href="#{{ $locale }}"><span class="lang-xs lang-lbl" lang="{{ $locale }}"></span></a>
                </li>
            @endforeach

        </ul>
        <div class="tab-content">

            @foreach($locales as $locale)
                <div role="tabpanel" id="{{ $locale }}" class="tab-pane {{ $locale == $fallback ? 'active' : '' }}">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <div class="form-group{{ $errors->has("name.$locale") ? ' has-error' : '' }}">
                                <label for="name-{{ $locale }}">{{ __('Name') }}</label>
                                <input type="text" name="name[{{ $locale }}]" class="form-control" id="name-{{ $locale }}" placeholder="{{ __('Name') }}" value="{{ old("name.$locale") }}">
                                @if ($errors->has("name.$locale"))
                                    <span class="help-block">
                                        <strong>{{ ucfirst($errors->first("name.$locale")) }}</strong>
                                    </span>
                                @endif
                            </div>
                            <div class="form-group{{ $errors->has("description.$locale") ? ' has-error' : '' }}">
                                <label for="description-{{ $locale }}">{{ __('Description') }}</label>
                                <textarea class="form-control not-resizable" name="description[{{ $locale }}]" id="description-{{ $locale }}" rows="15" placeholder="{{ __('Description') }}">{{ old("description.$locale") }}</textarea>
                                @if ($errors->has("description.$locale"))
                                    <span class="help-block">
                                        <strong>{{ ucfirst($errors->first("description.$locale")) }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                    </div>
                </div>
            @endforeach

            @component('layout.partials.panel')
                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group{{ $errors->has('price') ? ' has-error' : '' }}">
                            <label for="price">{{ __('Price') }}</label>
                            <div class="input-group">
                                <span class="input-group-addon">&euro;</span>
                                <input type="number" name="price" class="form-control" id="price" placeholder="{{ __('Price') }}" value="{{ old('price') }}">
                            </div>
                            @if ($errors->has('price'))
                                <span class="help-block">
                                    <strong>{{ ucfirst($errors->first('price')) }}</strong>
                                </span>
                            @endif
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group{{ $errors->has('lessons') ? ' has-error' : '' }}">
                            <label for="lessons">{{ __('Lessons') }}</label>
                            <input type="number" name="lessons" class="form-control" id="lessons" placeholder="{{ __('Lessons') }}" value="{{ old('lessons') }}">
                            @if ($errors->has('lessons'))
                                <span class="help-block">
                                    <strong>{{ ucfirst($errors->first('lessons')) }}</strong>
                                </span>
                            @endif
                        </div>
                    </div>
                </div>
                <div class="form-group{{ $errors->has('visible') ? ' has-error' : '' }}">
                    <label>{{ __('Visibility') }}</label>
                    <div class="btn-group btn-group-justified" data-toggle="buttons">
                        <label class="btn btn-default active">
                            <input type="radio" name="visible" value="1" checked> {{ __('Visible') }}
                        </label>
                        <label class="btn btn-default">
                            <input type="radio" name="visible" value="0"> {{  __('Invisible') }}
                        </label>
                    </div>
                    @if ($errors->has('visible'))
                        <span class="help-block">
                            <strong>{{ ucfirst($errors->first('visible')) }}</strong>
                        </span>
                    @endif
                </div>
            @endcomponent
        </div>
        <div class="text-right">
            <button type="submit" class="btn btn-primary">{{ __('Add Course') }}</button>
        </div>
    </form>
@endsection

@include('layout.partials.ckeditor', ['textareas' => array_map(function($locale) { return "description[$locale]";}, $locales)])

resources/views/admin/courses/edit.blade.php
@extends('layout.admin')

@section('meta')
    <title>{{ config('app.name') }} - {{ __('Edit Course') }} - {{ $course->asLocale('name') }}</title>
@endsection

@section('content')
    <form action="{{ route('courses.update', $course->id) }}" method="post">
        {{ csrf_field() }}
        {{ method_field('PATCH') }}
        <ul class="nav nav-tabs" role="tablist">
            @foreach($locales as $locale)
                <li role="presentation" {!! $locale == $fallback ? 'class="active"' : '' !!}>
                    <a role="tab" aria-controls="{{ $locale }}" data-toggle="tab" href="#{{ $locale }}"><span class="lang-xs lang-lbl" lang="{{ $locale }}"></span></a>
                </li>
            @endforeach
        </ul>
        <div class="tab-content">

            @foreach($locales as $locale)
                <div role="tabpanel" id="{{ $locale }}" class="tab-pane {{ $locale == $fallback ? 'active' : '' }}">
                    @component('layout.partials.panel')
                        <div class="form-group{{ $errors->has("name.$locale") ? ' has-error' : '' }}">
                            <label for="name-{{ $locale }}">{{ __('Name') }}</label>
                            <input type="text" name="name[{{ $locale }}]" class="form-control" id="name-{{ $locale }}" placeholder="{{ __('Name') }}" value="{{ old("name.$locale", $course->name[$locale]) }}">
                            @if ($errors->has("name.$locale"))
                                <span class="help-block">
                                    <strong>{{ ucfirst($errors->first("name.$locale")) }}</strong>
                                </span>
                            @endif
                        </div>
                        <div class="form-group{{ $errors->has("description.$locale") ? ' has-error' : '' }}">
                            <label for="description-{{ $locale }}">{{ __('Description') }}</label>
                            <textarea class="form-control not-resizable" name="description[{{ $locale }}]" id="description-{{ $locale }}" rows="15" placeholder="{{ __('Description') }}">{{ old("description.$locale", $course->description[$locale]) }}</textarea>
                            @if ($errors->has("description.$locale"))
                                <span class="help-block">
                                    <strong>{{ ucfirst($errors->first("description.$locale")) }}</strong>
                                </span>
                            @endif
                        </div>
                    @endcomponent
                </div>
            @endforeach

            @component('layout.partials.panel')
                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group{{ $errors->has('price') ? ' has-error' : '' }}">
                            <label for="price">{{ __('Price') }}</label>
                            <div class="input-group">
                                <span class="input-group-addon">&euro;</span>
                                <input type="number" name="price" class="form-control" id="price" placeholder="{{ __('Price') }}" value="{{ old('price', $course->price) }}">
                            </div>
                            @if ($errors->has('price'))
                                <span class="help-block">
                                    <strong>{{ ucfirst($errors->first('price')) }}</strong>
                                </span>
                            @endif
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group{{ $errors->has('lessons') ? ' has-error' : '' }}">
                            <label for="lessons">{{ __('Lessons') }}</label>
                            <input type="number" name="lessons" class="form-control" id="lessons" placeholder="{{ __('Lessons') }}" value="{{ old('lessons', $course->lessons) }}">
                            @if ($errors->has('lessons'))
                                <span class="help-block">
                                    <strong>{{ ucfirst($errors->first('lessons')) }}</strong>
                                </span>
                            @endif
                        </div>
                    </div>
                </div>
                <div class="form-group{{ $errors->has('visible') ? ' has-error' : '' }}">
                    <label>{{ __('Visibility') }}</label>
                    <div class="btn-group btn-group-justified" data-toggle="buttons">
                        <label class="btn btn-default {{ $course->visible ? 'active' : '' }}">
                            <input type="radio" name="visible" value="1" {{ $course->visible ? 'checked' : '' }}> {{ __('Visible') }}
                        </label>
                        <label class="btn btn-default {{ $course->visible ?: 'active' }}">
                            <input type="radio" name="visible" value="0" {{ $course->visible ?: 'checked' }}> {{  __('Invisible') }}
                        </label>
                    </div>
                    @if ($errors->has('visible'))
                        <span class="help-block">
                            <strong>{{ ucfirst($errors->first('visible')) }}</strong>
                        </span>
                    @endif
                </div>
            @endcomponent

        </div>
        <div class="text-right">
            <button id="delete-button" class="btn btn-danger">{{ __('Delete') }}</button>
            <button type="submit" class="btn btn-primary">{{ __('Edit Course') }}</button>
        </div>
    </form>
    <form id="delete-form" method="post" action="{{ route('courses.destroy', $course->id) }}">
        {{ csrf_field() }}
        {{ method_field('DELETE') }}
    </form>
@endsection

@include('layout.partials.ckeditor', ['textareas' => array_map(function($locale) { return "description[$locale]";}, $locales)])

@push('js')
    <script>
        $('#delete-button').click(function(e) {
            e.preventDefault();

            if(confirm('{{ __('Delete Course') }}?')) {
                $('#delete-form').submit();
            }
        });
    </script>
@endpush

resources/views/admin/courses/index.blade.php
@extends('layout.admin')

@section('meta')
    <title>{{ config('app.name') }} - {{ __('Courses') }}</title>
@endsection

@section('content')
    <div class="mb10 text-right">
        <a href="{{ route('courses.create') }}" target="_self">
            <button class="btn btn-primary">{{ __('Add Course') }}</button>
        </a>
    </div>

    @component('layout.partials.panel')
        <table id="courses" class="table table-striped table-hover table-responsive">
            <thead>
                <tr>
                    <th>{{ __('Name') }}</th>
                    <th>{{ __('Price') }}</th>
                    <th>{{ __('Lessons') }}</th>
                    <th>{{ __('Groups') }}</th>
                    <th>{{ __('Created at') }}</th>
                    <th>{{ __('Updated at') }}</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach($courses as $course)
                    <tr>
                        <td>{{ $course->asLocale('name') }}</td>
                        <td>&euro;{{ $course->price(false) }}</td>
                        <td>{{ $course->lessons }}</td>
                        <td><a href="{{ route('groups.index') }}?course={{ $course->id }}">{{ $course->groups_count }}</a></td>
                        <td>{{ $course->updated_at }}</td>
                        <td>{{ $course->created_at }}</td>
                        <td class="text-center">
                            <a href="{{ route('courses.edit', $course->id) }}" target="_self" title="{{ __('Visibility') }}"><span class="glyphicon glyphicon-{{ $course->visible ? 'eye-open text-primary' : 'eye-close text-muted' }}" aria-hidden="true"></span></a>
                            <a href="{{ route('courses.edit', $course->id) }}" target="_self" title="{{ __('Edit') }}"><span class="glyphicon glyphicon-edit" aria-hidden="true"></span></a>
                            <a class="delete" href="#delete" data-id="{{ $course->id }}" target="_self" title="{{ __('Delete') }}"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></a>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @endcomponent
@endsection

@include('layout.partials.datatables', ['table' => '#courses', 'features' => true])

@push('js')
    <script>
        $('.delete').click(function(e) {
            e.preventDefault();

            if (confirm('{{ __('Delete Course') }}?')) {
                $.ajax({
                    url: '/admin/courses/' + $(this).data('id'),
                    method: 'POST',
                    data: {
                        '_token': '{{ csrf_token() }}',
                        '_method': 'DELETE'
                    }
                }).done(function(data) {
                    this.closest('tr').remove();
                    alertify.notify(data.message, data.status);
                }.bind(this));
            }
        })
    </script>
@endpush